### ISSUE TITLE
CoffeeScript version insanity

### ISSUE THREAD

**Issue by thedufer** [trello/node-coffee-cache#2]
I had a thought on the CoffeeScript versioning issue.  With the new changes, obviously, this kinda breaks if CoffeeScript isn't installed somewhere require is searching.

What if we force `require` to do what we want, instead of what it usually does?  Normally, it searches locally and works its way up to the root of the filesystem.  However, we have access to the parent's module, so we can do something of the reverse by iterating up to the highest-level parent, and then trying to require on the way back down until we find a coffee-script version.  This will likely result in getting the one the user wants.  However, in case it doesn't, we can expose a function that takes a module (or a coffee-script) so the user can force the intended behavior.

What we do now:

    var coffee;
    try {
      coffee = require('coffee-script');
    } catch (e) {
      // No coffee-script installed in the project; warn them and stop
      process.stderr.write("coffee-cache: No coffee-script package found.\n");
      return;
    }

What we could be doing:

    function findCoffee(curModule) {
      var coffee;
      if (curModule.parent)
        coffee = findCoffee(curModule.parent);
      if (coffee)
        return coffee;
      try {
        return curModule.require('coffee-script')
      } catch (e) {
        return;
      }
    }
    var coffee = findCoffee(module);

    module.exports.setCoffee = function(tCoffee) {
      coffee = tCoffee;
    }
    module.exports.findCoffee = function(tModule) {
      coffee = tModule.require('coffee-script');
    }

Then we put coffee-script back into coffee-cache's node_modules, and we have a fallback in case someone is trying to use coffee-script but decided that installing it in a sane place is just too much work.

**Comment by dpatti** [comment]
Given that no one else has complained about this in the past, oh, two years, I'm going to guess it's not a problem. I would expect this to only be used at the root install of an application.
